spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

app:
  client:
    url: http://localhost:4200/login
